title: "chopralab-news"
email:
description: "Copyright 2018, Gaurav Chopra Laboratory, Purdue University, Contact the College of Science at sciencehelp@purdue.edu for trouble accessing this page."
baseurl: "chopralab/website/news/"
url: "https://chopralab.github.io/"
twitter_username: "chopralab"
youtube_username: "chopralab"
exclude:
    - "HOW-TO-USE.txt"
    - "Gemfile"
    - "Gemfile.lock"

# Build settings
markdown: "kramdown"
theme: "minima"
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
